weights: yolov5s.pt
cfg: /home/jun/Github/Master-Thesis/Task1-DragonFruit-Detection/Yolo/yolov5/models/yolov5s.yaml
data: /home/jun/Github/Master-Thesis/Task1-DragonFruit-Detection/Yolo/yolov5/data/dragon_fruit.yaml
hyp: /home/jun/Github/Master-Thesis/Task1-DragonFruit-Detection/Yolo/yolov5/data/hyps/hyp.scratch-high.yaml
epochs: 100
batch_size: 32
imgsz: 300
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 24
project: runs/train
name: dragon-fruit
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/dragon-fruit
